version: '3'
services:
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
  voting-app:
    build:
      context: .
    ports:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PGUSER=${PGUSER}
      - PGHOST=postgres
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
    depends_on:
      - postgres
  reverse-proxy:
    image: nginx:1.21
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    depends_on:
      - voting-app
  api-doc:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi.yaml:/openapi.yaml
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/openapi.yaml
volumes:
  pgdata:
